name: metamask_flutter_mobile_connect
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  file: ^6.1.3
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.5
  walletconnect_dart: ^0.0.11
  google_fonts: ^3.0.1
  slider_button: ^2.0.0
  web3dart: ^2.3.5
  webview_flutter: ^4.8.0
  wallet_connect_v2: ^1.0.9
  connectivity_plus: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
   - assets/
